### ISSUE TITLE
Issue with 2.2

### ISSUE THREAD

**Issue by Yaazor** [DeveloperLancer/MCPack#3]
Since the most recent update, I've had an issue with including MCPack on my website, as it is now unable to get past this error :

`Fatal error: Declaration of DevLancer\MCPack\ConsoleRcon::sendCommand(string $command): bool must be compatible with Thedudeguy\Rcon::sendCommand($command) /vendor/dev-lancer/mc-pack/src/ConsoleRcon.php on line 21`

I feel like this could be related to a recent change that was made to the sendCommand function (requiring the $command param to be a string), which doesn't match the parent function.

This might also come from a mistake in my configuration, but as of now, I wasn't able to solve the issue on my side (even when switching back versions, which is kinda weird).

**Comment by jgniecki** [comment]
I have released a corrected version 2.2.1 which fixes this problem and restores the ConsoleRcon.php class to the state from version 2.0.1
Version less than 2.2 is free of this bug, you probably need to change versions in composer.lock
